### ISSUE TITLE
Migrate source code from CodePlex to here

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetIdentity#1]
Need to copy all the codes and branches from http://aspnetidentity.codeplex.com/ and import to here. CodePlex is shutting down very soon so we need to do this ASAP.

cc @ajcvickers @divega

**Comment by HaoK** [comment]
Ported via 9c48993a446288032f9824633e6dae81257da06e 

Only master existed on codeplex, so only 2.1 was open source

**Comment by OzBob** [comment]
FYI: 2.2.0 source is available here: https://github.com/aspnet/Identity/

but not 2.2.1 or 2.2.2 as are available in nuget: https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework/2.2.2/
