### ISSUE TITLE
FileVersion of Microsoft.AspNet.Identity.* 2.2.2 is listed as 0.0.0.0

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetIdentity#23]
Reported by a user on nuget.org:

> The file version of this library (Microsoft.AspNet.Identity.Core.dll, also Microsoft.AspNet.Identity.EntityFramework.dll and Microsoft.AspNet.Identity.Owin.dll) is set to 0.0.0.0 causing problems during update installations.
>
> The problem might originate from the internal version number being 2.2.2.70424.0, with the fourth component being larger than 65535.
>
> Can you rerelease this package with fixed version numbers?

Here is the info for 2.2.2 of `Microsoft.AspNet.Identity.Core.dll`

![image](https://user-images.githubusercontent.com/202643/55832330-31fbf400-5aca-11e9-8d4d-68c88de06f16.png)

**Comment by toadpiglet** [comment]
can't believe this has not been fixed yet.

**Comment by Eilon** [comment]
@toadpiglet is this causing a specific problem? So far this has been a very low priority issue because it's not clear that there is any negative impact of the issue (aside from looking silly).

**Comment by toadpiglet** [comment]
Hi Eilon,

It causes an installation issue when upgrading. WIX doesn't install the
file and so although everything looks fine, the installer is actually
broken. If it wasn't for specific manual installation upgrade tests the
only way we'd of found out about this was through customers moaning that
the software was broken.
so yeah, maybe not a massive issue as we can just not upgrade to the latest
version.

Cheers - Tony

**Comment by Eilon** [comment]
Ah, yes, installers do use the File Version property for doing upgrades so I agree this is problematic for that scenario. I think we hadn't seen many (any?) people use installers to deploy this file, so it wasn't a high priority. This file is mostly used in web apps, which are typically deployed via other means, as seen here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-3.0

BTW I don't work on this project anymore so I'll tag @Pilchie to see if the priority of this issue should be adjusted.

**Comment by Pilchie** [comment]
@joeloff has been looking at this today, as another customer reported through NuGet.  We think we know what happened, and might be able to publish a 2.2.2.3 with it fixed.

**Comment by joeloff** [comment]
@Eilon we actually have an installer that might be shipping this file too. We tracked the issue down.

**Comment by joeloff** [comment]
Actually, it has a file version, but it's completely invalid. It has 5 parts, instead of 4 and the 3rd part is completely outside the valid range (0..65535)

[assembly: AssemblyFileVersion("2.2.2.70424.0")]

**Comment by toadpiglet** [comment]
Ah OK, thanks for looking into it.

**Comment by dbenzhuser** [comment]
I was the original reporter on Nuget.org mentioned above. We currently ship a Microsoft.AspNet.Identity.Core.dll with a manually patched file version to get updates to work.

Fixed version would be welcome, one less special case to remember not to break ...

**Comment by brettzook** [comment]
I too discovered the faulty file version when these DLLs were not installed while running an update of a WIX-based installer.

@Pilchie what's the likelihood of a new package being published in the near future?

**Comment by joeloff** [comment]
@brettzook, we're working on it.

**Comment by joeloff** [comment]
Forgot about closing this. @brettzook we uploaded the 2.2.3 packages to NuGet.

**Comment by brettzook** [comment]
Yes, I noticed that a day or so after it was available. Thank you!
