### ISSUE TITLE
Conflict between Identity class and its extended one.

### ISSUE THREAD

**Issue by embryologist** [aspnet/AspNetIdentity#6]
I am trying to add a shadow property to all my tables using the following code in my builder override,

```C#
foreach (var entityType in builder.Model.GetEntityTypes ()) {
        entityType.GetOrAddProperty ("IsDeleted", typeof (bool));
        var parameter = Expression.Parameter (entityType.ClrType);
        var propertyMethodInfo = typeof (EF).GetMethod ("Property").MakeGenericMethod (typeof (bool));
        var isDeletedProperty = Expression.Call (propertyMethodInfo, parameter, Expression.Constant ("IsDeleted"));
        BinaryExpression compareExpression = Expression.MakeBinary (ExpressionType.Equal, isDeletedProperty, Expression.Constant (false));
        var lambda = Expression.Lambda (compareExpression, parameter);
        builder.Entity (entityType.ClrType).HasQueryFilter (lambda);
 }
```

I have This "ApplicationRole" class which extends the IdentityRole,
```C#
    public class ApplicationRole : IdentityRole {
        public string Description { get; set; }

        [Required]
        public Guid DatabaseId { get; set; }

        [ForeignKey ("DatabaseId")]
        public virtual PracticeDatabase Database { get; set; }
    }
```
How can I resolve this conflict?

currently I resolve it by exlcuding the extended class as follows,

```C#
  if (entityType.Name == "ArtNgCore.Core.Models.IdentityModels.ApplicationRole") {
      return;
    }

```
is there another way ?

The conflict message is,

> System.InvalidOperationException: The property or navigation 'IsDeleted' cannot be added to the entity type 'IdentityRole' because a property or navigation with the same name already exists on entity type 'ApplicationRole'.
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(String name, Type propertyType, MemberInfo memberInfo, ConfigurationSource configurationSource, Nullable`1 typeConfigurationSource)
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(String name, Type propertyType, ConfigurationSource configurationSource, Nullable`1 typeConfigurationSource)
>    at ArtNgCore.Persistence.Core.ArtCoreDbContext.OnModelCreating(ModelBuilder builder) in /Users/json/OneDrive/MyProjects/ArtNgCore/Persistence/Core/ArtCoreDbContext.cs:line 68
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>    at System.Lazy`1.CreateValue()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> The property or navigation 'IsDeleted' cannot be added to the entity type 'IdentityRole' because a property or navigation with the same name already exists on entity type 'ApplicationRole'

**Comment by HaoK** [comment]
@ajcvickers any ideas what this could be?

**Comment by ajcvickers** [comment]
@embryologist Only add it to base types. That is, when IEntityType.BaseType is null.

**Comment by embryologist** [comment]
@ajcvickers , I tried this,

```
public class ApplicationUserRoles : IdentityUserRole<string>, ISoftDelete {
        public bool IsDeleted { get; set; }
    }
```
And I changed my filter to,

```
                        foreach (IMutableEntityType entityType in builder.Model.GetEntityTypes ()) {
                                IMutableProperty IsDeleted = entityType.FindProperty ("IsDeleted");
                                MethodInfo propertyMethodInfo = typeof (EF).GetMethod ("Property").MakeGenericMethod (typeof (bool));
                                if (IsDeleted != null && IsDeleted.ClrType == typeof (bool)) {
                                        ParameterExpression parameter = Expression.Parameter (entityType.ClrType, "p");
                                        MethodCallExpression isDeletedProperty = Expression.Call (propertyMethodInfo, parameter, Expression.Constant ("IsDeleted"));
                                        BinaryExpression compareExpression = Expression.MakeBinary (ExpressionType.Equal, isDeletedProperty, Expression.Constant (false));
                                        LambdaExpression filter = (Expression.Lambda (compareExpression, parameter));
                                        entityType.QueryFilter = filter;
                                }
                        }
```

The filter expression 'p => (Property(p, "IsDeleted") == False)' cannot be specified for entity type 'ApplicationUserRoles'. A filter may only be applied to the root entity type in a hierarchy.

isn't this what you were talking about?
